name: CI
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, labeled, synchronize]
env:
  NODE_ENV: 'TEST'
  GAS_REPORT: 'true'
  ARB_SEPOLIA_ETHERSCAN_API_KEY: ${{ secrets.ARB_SEPOLIA_ETHERSCAN_API_KEY }}
  COINMARKETCAP_KEY: ${{ secrets.COINMARKETCAP_KEY }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/setup'
      - name: Building
        run: pnpm build
      - name: Linting
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: './.github/setup'

      - name: Running tests
        run: pnpm test:parallel
